# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Laurence de Torrente
tagline:          'A Jekyll theme'
description:      'Research Fellow in the Systems and Computational Biology Department at Albert Einstein College of Medicine.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Laurence de Torrente'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/detorrentel
