# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Laurence de Torrente
tagline:          'Research Fellow'
description:      ''
url:              http://http://detorrentel.github.io
baseurl:          /

author:
  name:           'Laurence de Torrente'
  url:            
  email:          laurence.detorrente@gmail.com
paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/detorrentel
  
  #social links
github_user: detorrentel
linkedin_user: laurencedetorrente
